name: Acceptance Tests

on:
    release:
      paths-ignore:
        - 'README.md'
        - 'docs/**'
        - 'templates/**'

jobs:
  acceptance:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    environment: api-integ-test-eu
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - 0.15.0
          - 1.0.0
    steps:
      - name: Set up Go
        id: go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run tests
        env:
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
          KTAPI_AUTH_EMAIL: ${{ secrets.KTAPI_AUTH_EMAIL }}
          KTAPI_AUTH_TOKEN: ${{ secrets.KTAPI_AUTH_TOKEN }}
          KTAPI_URL: ${{ secrets.KTAPI_URL }}
          KENTIK_PLAN_ID: ${{ secrets.KENTIK_PLAN_ID }}
        run: make acceptance
